Testing framework and initial tests
parsa-epfl/libqflex pull request #14
Opened 2024-07-12 12:54 UTC by ounuvar

Added a testing framework and initial tests for the memory decoder. Two classes called Field and Instruction in the testing-utils.hh file form the testing framework. Some of the initial tests currently fail because of bugs in the memory decoder, and the correct decoder outputs for some instructions (like prefetch instructions) are ambiguous.

2024-07-15 09:43 UTC, branylagaffe requested changes
Overall good.

Few design flaw. Few coding mistakes.

However, the comments are to improve. They are usually shallow and only reflect the meaning of the function name or the next line. Comments should indicate to the reader the possible state of the variable, why we need this function, the limitations of the function, any kind of asserted input/output.

2024-07-15 09:43 UTC, branylagaffe commented on testing/CMakeLists.txt
As somewhat expected, the tests do not build OOTB, because the decoder require some qemu includes (osdep).
Two options from here:
    1. Add a FLAG from the CmakeList.txt file which switch the header in the aforementioned files
    2. Use QEMU build system to build the test, tricky but good.

2024-07-15 09:43 UTC, branylagaffe commented on testing/testing-utils.hh
> +#include <iostream>
Some of these include are not needed anymore

2024-07-15 09:43 UTC, branylagaffe commented on testing/testing-utils.hh
> +        int currIter;
Use coherently  the std defined integer (uint8_t, size_t, ....) and c++ defined integer (int, long).
I guess we can use the std defined ones here

2024-07-15 09:43 UTC, branylagaffe commented on testing/testing-utils.hh
> +    std::vector<Field*> fields;
Any reason to use raw pointer instead of reference here ?

2024-07-15 09:43 UTC, branylagaffe commented on testing/testing-utils.hh
> +    // Variadic template function to add fields (Field objects or string literals) to the instruction
`variadic` is not an English word

```suggestion
    // specialized function ..
```

2024-07-15 09:43 UTC, branylagaffe commented on testing/testing-utils.hh
> +    // Terminal function for the variadic template addFields
`variadic` is not an English word

2024-07-15 09:43 UTC, branylagaffe commented on testing/testing-utils.cc
> +bool isBitmask(const std::string& str) {
Any reason why these functions are not static member of the Field class ?

2024-07-15 09:43 UTC, branylagaffe commented on testing/testing-utils.cc
> +  fields.push_back(new Field(str));
Memory leak here, they are never deleted

2024-07-15 09:43 UTC, branylagaffe commented on testing/testing-utils.cc
> +  fields.push_back(new Field(str));
Pretty sure the `Field` could be copied or moved instead of pointer sharing

2024-07-15 09:43 UTC, branylagaffe commented on testing/testing-utils.cc
> +    bitmask += field->bitmask;
Pretty sure accumulate can work here
https://en.cppreference.com/w/cpp/algorithm/accumulate

2024-07-15 09:43 UTC, branylagaffe commented on testing/testing-utils.cc
> +  assert(bitmask.size() == 32 && "Bitmask size must be 32.");
Your assert is wrongly defined.
```cpp
  assert((void("void helps to avoid 'unused value' warning"), 2 * 2 == 4));
  OR
  assert((010 + 010 == 16) && "Yet another way to add an assert message");
  OR
  assertm((2 + 2) % 3 == 1, "Success");
```
Notice the parentheses around the expression

2024-07-15 09:43 UTC, branylagaffe commented on testing/testing-utils.cc
> +  int numDontCares = std::count(bitmask.begin(), bitmask.end(), 'x');
Type coherence

2024-07-15 09:43 UTC, branylagaffe commented on testing/testing-utils.cc
> +  for (int i = 0, j = 0; i < 32; ++i) {
Avoid hardcoded number (32, 31)

2024-07-15 09:43 UTC, branylagaffe commented on testing/testing-utils.cc
> +uint32_t Instruction::InstructionIterator::operator*() const {
I don't understand why the dereference operator is link to generating an instruction, Shall not the instruction get pre-processed and retrieved by the deref. operator

2024-07-15 09:43 UTC, branylagaffe commented on testing/testing-utils.cc
> +  // Generate the instruction based on the bitmask
This loop should be a function in Instruction instead of the Iterator.
The loop is slightly unintuitive (basically everything with bitwise operator is); i would suggest decoupling this loop into more functions

2024-07-15 09:54 UTC, ounuvar commented on testing/CMakeLists.txt
Could you elaborate on the second option? How would it work?

2024-07-15 09:54 UTC, ounuvar commented on testing/testing-utils.hh
> +#include <iostream>
You're right. Fixing.

2024-07-15 09:55 UTC, ounuvar commented on testing/testing-utils.hh
> +        int currIter;
Fixing.

2024-07-15 09:58 UTC, ounuvar commented on testing/testing-utils.hh
> +    std::vector<Field*> fields;
Apparently, we can't store references inside containers like vector in C++. I guess I could use a reference_wrapper object here as well (just like the void Instruction::addField(std::reference_wrapper<Field> field) function in testing-utils.cc). That might make even more sense actually since we already take the arguments as reference_wrapper objects.

2024-07-15 09:59 UTC, ounuvar commented on testing/testing-utils.hh
> +    // Variadic template function to add fields (Field objects or string literals) to the instruction
Variadic is the correct technical term I believe: https://en.wikipedia.org/wiki/Variadic

2024-07-15 10:01 UTC, ounuvar commented on testing/testing-utils.cc
> +  assert(bitmask.size() == 32 && "Bitmask size must be 32.");
== should have higher precedence than && but will add the parentheses just to make it clearer.

2024-07-15 10:03 UTC, ounuvar commented on testing/testing-utils.cc
> +  int numDontCares = std::count(bitmask.begin(), bitmask.end(), 'x');
Are you again referring to the use of builtin `int` instead of stdint types? (Or the lack of consisteny in the usage?)

2024-07-15 10:04 UTC, ounuvar commented on testing/testing-utils.cc
> +  for (int i = 0, j = 0; i < 32; ++i) {
Fixing.

2024-07-15 10:06 UTC, ounuvar commented on testing/testing-utils.cc
> +uint32_t Instruction::InstructionIterator::operator*() const {
Wdym by pre-processed? The exact instruction bits (the uint32_t value) for each iteration in `for (uint32_t instr : bitmask)`  is generated during runtime through the dereference operator.

2024-07-15 10:11 UTC, ounuvar commented on testing/testing-utils.cc
> +  // Generate the instruction based on the bitmask
The dereference operator (method) needs to be defined for the Iterator class. I could move the logic to a separate helper function in the Instruction class (and also maybe divide it into multiple functions in the meantime like you said) and call it from the dereference operator in the Iterator class.

2024-07-15 15:41 UTC, branylagaffe commented on testing/testing-utils.cc
> +  // Generate the instruction based on the bitmask
Yep the deref. operator is needed for the Iterator, no question. As you said the logic should be moved elsewhere, and maybe pre-processed

2024-07-16 15:36 UTC, ounuvar commented on testing/testing-utils.cc
> +  fields.push_back(new Field(str));
Neither copy or move works for our use case, so we need pointer sharing. I got rid of the memory leak by using shared_ptr instead.

2024-07-16 15:37 UTC, ounuvar commented on testing/testing-utils.cc
> +    bitmask += field->bitmask;
Okay, changing to use accumulate.

2024-07-17 01:13 UTC, ounuvar commented on testing/CMakeLists.txt
Implemented the first option for now.

2025-01-22 12:10 UTC, closed without merging